"use client";

import { useEffect, useState } from "react";
import ChatBubble from "@/components/interview/ChatBubble";
import type { AppSupabaseClient } from "@/components/interview/types";
import type { Member, PsLabel, PsStatement } from "@/types/database";
import { PS_COLOR_DOT, PS_LABEL_WORD, psColorGroup } from "@/lib/psLabels";
import { propagateDisplayNameChange } from "@/lib/memberRename";

type ShareChoice = "private" | "open";

function choiceFromMember(m: Member): ShareChoice | null {
  if (m.share_verbatim_with_team && m.share_name_with_team) return "open";
  if (!m.share_verbatim_with_team && !m.share_name_with_team) return "private";
  return null;
}

function buildPrintableHTML(
  member: Member,
  purposeText: string,
  psStatements: PsStatement[],
  psRatings: Record<number, PsLabel>,
  rosterMissingName: string,
  rosterMissingRole: string,
  rosterNoted: boolean,
  ownRoleText: string,
  psImportanceText: string
): string {
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const consentText =
    choiceFromMember(member) === "open"
      ? "Sharing my exact words with my team, shown under a random ID (not my name)"
      : "Keeping responses fully private";

  const psSection = psStatements
    .map((s) => {
      const rating = psRatings[s.statement_id];
      const symbol = rating ? PS_COLOR_DOT[psColorGroup(s, rating)] : "○";
      const word = rating ? PS_LABEL_WORD[rating] : "Not answered";
      return `<tr>
        <td style="padding:6px 8px;border-bottom:1px solid #eee;font-size:14px">${s.statement_text}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #eee;font-size:14px;white-space:nowrap">${symbol} ${word}</td>
      </tr>`;
    })
    .join("");

  const missingRow =
    rosterNoted && rosterMissingName
      ? `<p style="font-size:14px;color:#555">I flagged that <strong>${rosterMissingName}</strong>${rosterMissingRole ? ` (${rosterMissingRole})` : ""} may be missing from the team roster.</p>`
      : "";

  const demographics = [
    member.primary_language ? `Language: ${member.primary_language}` : null,
    member.gender_identity ? `Gender identity: ${member.gender_identity}` : null,
    member.ethnicity_cultural ? `Cultural background: ${member.ethnicity_cultural}` : null,
    member.age ? `Age: ${member.age}` : null,
    member.personal_context ? `Other context: ${member.personal_context}` : null,
  ]
    .filter(Boolean)
    .join("<br>");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>My Otis session — ${member.display_name}</title>
<style>
  body{font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;max-width:760px;margin:0 auto;padding:40px 32px;color:#1F1F1F;line-height:1.5}
  h1{color:#6B4EA8;margin-bottom:4px}
  h2{color:#1A1A2E;font-size:16px;text-transform:uppercase;letter-spacing:.06em;border-bottom:2px solid #eee;padding-bottom:6px;margin-top:36px}
  table{width:100%;border-collapse:collapse;margin-top:8px}
  td{vertical-align:top}
  .meta{color:#6B6B6B;font-size:14px;margin-bottom:8px}
  @media print{body{padding:16px}h2{page-break-after:avoid}}
</style>
</head>
<body>
<h1>My Otis session</h1>
<p class="meta">${member.display_name} · ${date}</p>

<h2>Privacy choice</h2>
<p style="font-size:14px">${consentText}</p>

<h2>Profile</h2>
<p style="font-size:14px">
  <strong>${member.display_name}</strong><br>
  ${[member.role, member.location, member.timezone].filter(Boolean).join(" · ")}<br>
  ${member.tenure_start ? `Joined: ${member.tenure_start}<br>` : ""}
  ${demographics || ""}
</p>

${ownRoleText ? `<h2>My role on the team</h2><p style="font-size:14px">${ownRoleText}</p>` : ""}

<h2>Shared purpose</h2>
<p style="font-size:14px">${purposeText || "<em>Not answered</em>"}</p>

${missingRow ? `<h2>Roster note</h2>${missingRow}` : ""}

${psImportanceText ? `<h2>Is PS important to my team?</h2><p style="font-size:14px">${psImportanceText}</p>` : ""}

<h2>Psychological safety — 12 statements</h2>
<table>${psSection}</table>

<p style="margin-top:48px;font-size:12px;color:#999">Generated by Otis · wavelength-app.vercel.app</p>
</body>
</html>`;
}

function ConsentCard({
  choice,
  selected,
  onSelect,
}: {
  choice: ShareChoice;
  selected: boolean;
  onSelect: () => void;
}) {
  const label =
    choice === "private"
      ? "Keep my responses fully private — describe patterns, don't quote me, don't attach my name."
      : "I'm comfortable sharing my exact words with my team — shown under a random ID, not my name — as a step toward open conversation.";

  return (
    <button
      type="button"
      onClick={onSelect}
      aria-pressed={selected}
      className={`card w-full text-left py-4 flex items-start gap-4 transition-colors border-2 ${
        selected
          ? "border-[var(--color-purple)] bg-[var(--color-purple)]/5"
          : "border-transparent"
      }`}
    >
      <span
        className={`mt-0.5 flex-shrink-0 h-5 w-5 rounded-full border-2 flex items-center justify-center text-xs ${
          selected
            ? "border-[var(--color-purple)] bg-[var(--color-purple)] text-white"
            : "border-black/20 text-transparent"
        }`}
      >
        ✓
      </span>
      <span>{label}</span>
    </button>
  );
}

function InlineEdit({
  value,
  onSave,
  multiline,
  placeholder,
}: {
  value: string;
  onSave: (next: string) => Promise<void>;
  multiline?: boolean;
  placeholder?: string;
}) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(value);
  const [saving, setSaving] = useState(false);

  async function handleSave() {
    setSaving(true);
    await onSave(draft);
    setSaving(false);
    setEditing(false);
  }

  if (!editing) {
    return (
      <div className="flex items-start gap-2">
        <p className="text-sm text-[var(--color-grey)] flex-1">
          {value || <em>Not answered.</em>}
        </p>
        <button
          type="button"
          onClick={() => { setDraft(value); setEditing(true); }}
          className="text-xs text-[var(--color-purple)] underline flex-shrink-0"
        >
          Edit
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-2">
      {multiline ? (
        <textarea
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          rows={4}
          className="form-input resize-none"
          placeholder={placeholder}
        />
      ) : (
        <input
          type="text"
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          className="form-input"
          placeholder={placeholder}
        />
      )}
      <div className="flex gap-2">
        <button
          type="button"
          onClick={handleSave}
          disabled={saving}
          className="text-xs bg-[var(--color-navy)] text-white px-3 py-1.5 rounded-full"
        >
          {saving ? "Saving…" : "Save"}
        </button>
        <button
          type="button"
          onClick={() => setEditing(false)}
          className="text-xs text-[var(--color-grey)] underline"
        >
          Cancel
        </button>
      </div>
    </div>
  );
}

export default function ReviewStep({
  member,
  psStatements,
  psRatings,
  purposeText,
  rosterMissingName,
  rosterMissingRole,
  rosterNoted,
  ownRoleText,
  psImportanceText,
  readAloud,
  supabase,
  onSaved,
  onAdvance,
}: {
  member: Member;
  psStatements: PsStatement[];
  psRatings: Record<number, PsLabel>;
  purposeText: string;
  rosterMissingName: string;
  rosterMissingRole: string;
  rosterNoted: boolean;
  ownRoleText: string;
  psImportanceText: string;
  readAloud: boolean;
  supabase: AppSupabaseClient;
  onSaved: (fields: Partial<Member>) => void;
  onAdvance: () => void;
}) {
  const [consentChoice, setConsentChoice] = useState<ShareChoice | null>(
    choiceFromMember(member)
  );
  const [savingConsent, setSavingConsent] = useState(false);
  const [consentError, setConsentError] = useState<string | null>(null);

  const [ratings, setRatings] = useState<Record<number, PsLabel>>(psRatings);
  const [purpose, setPurpose] = useState<string>(purposeText);
  const [missingName, setMissingName] = useState(rosterMissingName);
  const [missingRole, setMissingRole] = useState(rosterMissingRole);
  // Editable copies backed by members.own_role / members.ps_importance.
  const [ownRole, setOwnRole] = useState(ownRoleText);
  const [psImportance, setPsImportance] = useState(psImportanceText);
  // Demographics — backed by members table, editable here.
  const [lang, setLang] = useState(member.primary_language ?? "");
  const [gender, setGender] = useState(member.gender_identity ?? "");
  const [ethnicity, setEthnicity] = useState(member.ethnicity_cultural ?? "");
  const [age, setAge] = useState(member.age ?? "");
  const [personalCtx, setPersonalCtx] = useState(member.personal_context ?? "");

  // Fetch from DB when draft values are absent (member resumed directly to review).
  useEffect(() => {
    async function load() {
      if (Object.keys(psRatings).length === 0) {
        const { data: psRows } = await supabase
          .from("ps_responses")
          .select("statement_id, label")
          .eq("member_id", member.member_id)
          .eq("round", 1);
        const map: Record<number, PsLabel> = {};
        for (const row of psRows ?? []) map[row.statement_id] = row.label as PsLabel;
        setRatings(map);
      }

      if (!purposeText) {
        const { data: purposeRow } = await supabase
          .from("purpose_responses")
          .select("purpose_text")
          .eq("member_id", member.member_id)
          .maybeSingle();
        if (purposeRow?.purpose_text) setPurpose(purposeRow.purpose_text);
      }

      if (!rosterNoted) {
        const { data: flagRow } = await supabase
          .from("missing_member_flags")
          .select("missing_name, missing_role")
          .eq("reported_by_member_id", member.member_id)
          .maybeSingle();
        if (flagRow?.missing_name) {
          setMissingName(flagRow.missing_name);
          setMissingRole(flagRow.missing_role ?? "");
        }
      }
    }
    load().catch((e) => console.error("[interview/review] load failed:", e));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function selectConsent(next: ShareChoice) {
    setConsentChoice(next);
    setSavingConsent(true);
    setConsentError(null);

    const fields =
      next === "open"
        ? { share_verbatim_with_team: true, share_name_with_team: true }
        : { share_verbatim_with_team: false, share_name_with_team: false };

    const { error: updateError } = await supabase
      .from("members")
      .update(fields)
      .eq("member_id", member.member_id);

    if (updateError) {
      console.error("[interview/review] failed to save consent change:", {
        message: updateError.message,
        code: updateError.code,
      });
      setConsentError("Couldn't save your change — please try again.");
    } else {
      onSaved(fields);
    }
    setSavingConsent(false);
  }

  async function savePurpose(next: string) {
    const { data: existing } = await supabase
      .from("purpose_responses")
      .select("id")
      .eq("member_id", member.member_id)
      .maybeSingle();

    if (existing) {
      await supabase
        .from("purpose_responses")
        .update({ purpose_text: next })
        .eq("member_id", member.member_id);
    } else {
      await supabase
        .from("purpose_responses")
        .insert({ member_id: member.member_id, team_id: member.team_id, purpose_text: next });
    }
    setPurpose(next);
  }

  async function saveProfileField(fields: Partial<Member>) {
    await supabase.from("members").update(fields).eq("member_id", member.member_id);
    // If the display name changed, repoint ratings other members gave this member
    // under the old name (coordination_ratings stores names, not ids).
    if (fields.display_name && fields.display_name !== member.display_name) {
      await propagateDisplayNameChange(
        supabase,
        member.team_id,
        member.display_name,
        fields.display_name
      );
    }
    onSaved(fields);
  }

  function handleDownload() {
    const html = buildPrintableHTML(
      member,
      purpose,
      psStatements,
      ratings,
      missingName,
      missingRole,
      rosterNoted || !!missingName,
      ownRoleText,
      psImportanceText
    );
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(html);
    w.document.close();
    setTimeout(() => w.print(), 400);
  }

  function handleEmail() {
    const subject = encodeURIComponent("My Otis session");
    const body = encodeURIComponent(
      `Hi,\n\nI completed a Otis team interview and wanted to keep a copy.\n\nFor the full formatted version, please use the Download / Print button on the review screen.\n\n— ${member.display_name}`
    );
    window.open(`mailto:${member.email ?? ""}?subject=${subject}&body=${body}`);
  }


  return (
    <div className="space-y-10">
      <div>
        <ChatBubble readAloud={readAloud} hideAvatar>
          Before we end, take a look to see if there&apos;s anything you want
          to edit. You can download this information, or find it again by
          logging into your profile.
        </ChatBubble>
        <div className="flex flex-wrap gap-3 mt-4">
          <button type="button" onClick={handleDownload} className="btn-secondary">
            ↓ Download / Print
          </button>
          {member.email && (
            <button type="button" onClick={handleEmail} className="btn-secondary">
              ✉ Email me a copy
            </button>
          )}
        </div>
      </div>

      {/* Profile */}
      <section>
        <h2 className="text-2xl mb-4">Your profile</h2>
        <div className="card space-y-3">
          <div>
            <p className="text-xs text-[var(--color-grey)] mb-1">Name</p>
            <InlineEdit
              value={member.display_name}
              onSave={(v) => saveProfileField({ display_name: v || member.display_name })}
            />
          </div>
          <div>
            <p className="text-xs text-[var(--color-grey)] mb-1">Role</p>
            <InlineEdit
              value={member.role ?? ""}
              onSave={(v) => saveProfileField({ role: v || null })}
              placeholder="e.g. Product Manager"
            />
          </div>
          <div>
            <p className="text-xs text-[var(--color-grey)] mb-1">Location</p>
            <InlineEdit
              value={member.location ?? ""}
              onSave={(v) => saveProfileField({ location: v || null })}
              placeholder="e.g. London"
            />
          </div>
          <div className="pt-2 border-t border-black/5 space-y-3">
            <div>
              <p className="text-xs text-[var(--color-grey)] mb-1">Language(s)</p>
              <InlineEdit
                value={lang}
                onSave={async (v) => {
                  await saveProfileField({ primary_language: v || null });
                  setLang(v);
                }}
                placeholder="e.g. English, Spanish..."
              />
            </div>
            <div>
              <p className="text-xs text-[var(--color-grey)] mb-1">Gender identity</p>
              <InlineEdit
                value={gender}
                onSave={async (v) => {
                  await saveProfileField({ gender_identity: v || null });
                  setGender(v);
                }}
                placeholder="e.g. woman, man, non-binary..."
              />
            </div>
            <div>
              <p className="text-xs text-[var(--color-grey)] mb-1">Cultural background</p>
              <InlineEdit
                value={ethnicity}
                onSave={async (v) => {
                  await saveProfileField({ ethnicity_cultural: v || null });
                  setEthnicity(v);
                }}
                placeholder="Describe in your own words..."
              />
            </div>
            <div>
              <p className="text-xs text-[var(--color-grey)] mb-1">Age</p>
              <InlineEdit
                value={age}
                onSave={async (v) => {
                  await saveProfileField({ age: v || null });
                  setAge(v);
                }}
                placeholder="e.g. 34"
              />
            </div>
            <div>
              <p className="text-xs text-[var(--color-grey)] mb-1">Other context</p>
              <InlineEdit
                value={personalCtx}
                onSave={async (v) => {
                  await saveProfileField({ personal_context: v || null });
                  setPersonalCtx(v);
                }}
                multiline
                placeholder="Anything else you shared..."
              />
            </div>
          </div>
        </div>
      </section>

      {/* Own role — persisted to members.own_role */}
      {(ownRole || ownRoleText) && (
        <section>
          <h2 className="text-2xl mb-4">Your role on the team</h2>
          <div className="card">
            <InlineEdit
              value={ownRole}
              onSave={async (v) => {
                await saveProfileField({ own_role: v.trim() || null });
                setOwnRole(v);
              }}
              multiline
              placeholder="Describe your role and what you contribute..."
            />
          </div>
        </section>
      )}

      {/* Purpose */}
      <section>
        <h2 className="text-2xl mb-4">Shared purpose</h2>
        <div className="card">
          <InlineEdit
            value={purpose}
            onSave={savePurpose}
            multiline
            placeholder="Describe your team's shared purpose..."
          />
        </div>
      </section>

      {/* Roster note */}
      {(rosterNoted || !!missingName) && (
        <section>
          <h2 className="text-2xl mb-4">Roster note</h2>
          <div className="card space-y-2">
            <InlineEdit
              value={missingName}
              onSave={async (v) => setMissingName(v)}
              placeholder="Name"
            />
            <InlineEdit
              value={missingRole}
              onSave={async (v) => setMissingRole(v)}
              placeholder="Role (optional)"
            />
          </div>
        </section>
      )}

      {/* PS Importance — persisted to members.ps_importance */}
      {(psImportance || psImportanceText) && (
        <section>
          <h2 className="text-2xl mb-4">Is PS important to your team?</h2>
          <div className="card">
            <InlineEdit
              value={psImportance}
              onSave={async (v) => {
                await saveProfileField({ ps_importance: v.trim() || null });
                setPsImportance(v);
              }}
              multiline
              placeholder="Share your thoughts on psychological safety..."
            />
          </div>
        </section>
      )}

      {/* PS Diagnostic */}
      <section>
        <h2 className="text-2xl mb-4">Psychological safety</h2>
        <div className="space-y-2">
          {psStatements.map((s) => {
            const rating = ratings[s.statement_id];
            return (
              <div
                key={s.statement_id}
                className="card py-3 flex items-start justify-between gap-4"
              >
                <p className="text-sm flex-1">{s.statement_text}</p>
                <span className="flex-shrink-0 text-sm whitespace-nowrap">
                  {rating ? (
                    <>
                      {PS_COLOR_DOT[psColorGroup(s, rating)]}{" "}
                      <span className="text-[var(--color-grey)]">
                        {PS_LABEL_WORD[rating]}
                      </span>
                    </>
                  ) : (
                    <span className="text-[var(--color-grey)]">—</span>
                  )}
                </span>
              </div>
            );
          })}
        </div>
      </section>

      {/* Editable consent */}
      <section>
        <h2 className="text-2xl mb-2">Your privacy choice</h2>
        <p className="text-[var(--color-grey)] text-sm mb-4">
          You can change this here — it takes effect immediately.
        </p>
        <div className="space-y-3">
          <ConsentCard
            choice="private"
            selected={consentChoice === "private"}
            onSelect={() => selectConsent("private")}
          />
          <ConsentCard
            choice="open"
            selected={consentChoice === "open"}
            onSelect={() => selectConsent("open")}
          />
        </div>
        {savingConsent && (
          <p className="text-sm text-[var(--color-grey)] mt-2">Saving…</p>
        )}
        {consentError && (
          <p className="text-sm text-[var(--color-grey)] mt-2">{consentError}</p>
        )}
      </section>

      <button type="button" onClick={onAdvance} className="btn-primary">
        Continue
      </button>
    </div>
  );
}
