// A small bundled list of major world cities with their IANA timezone, used
// to power the location autocomplete on the team members page. Deliberately
// static (no external API/library) so it's simple and reliable — this isn't
// meant to be exhaustive, just enough to auto-fill the common cases.
export type City = {
  city: string;
  country: string;
  timezone: string;
};

export const CITIES: City[] = [
  { city: "New York", country: "United States", timezone: "America/New_York" },
  { city: "Los Angeles", country: "United States", timezone: "America/Los_Angeles" },
  { city: "San Francisco", country: "United States", timezone: "America/Los_Angeles" },
  { city: "Seattle", country: "United States", timezone: "America/Los_Angeles" },
  { city: "Chicago", country: "United States", timezone: "America/Chicago" },
  { city: "Dallas", country: "United States", timezone: "America/Chicago" },
  { city: "Houston", country: "United States", timezone: "America/Chicago" },
  { city: "Austin", country: "United States", timezone: "America/Chicago" },
  { city: "Denver", country: "United States", timezone: "America/Denver" },
  { city: "Phoenix", country: "United States", timezone: "America/Phoenix" },
  { city: "Boston", country: "United States", timezone: "America/New_York" },
  { city: "Washington", country: "United States", timezone: "America/New_York" },
  { city: "Philadelphia", country: "United States", timezone: "America/New_York" },
  { city: "Miami", country: "United States", timezone: "America/New_York" },
  { city: "Atlanta", country: "United States", timezone: "America/New_York" },
  { city: "Honolulu", country: "United States", timezone: "Pacific/Honolulu" },
  { city: "Toronto", country: "Canada", timezone: "America/Toronto" },
  { city: "Montreal", country: "Canada", timezone: "America/Toronto" },
  { city: "Ottawa", country: "Canada", timezone: "America/Toronto" },
  { city: "Vancouver", country: "Canada", timezone: "America/Vancouver" },
  { city: "Calgary", country: "Canada", timezone: "America/Edmonton" },
  { city: "Mexico City", country: "Mexico", timezone: "America/Mexico_City" },
  { city: "São Paulo", country: "Brazil", timezone: "America/Sao_Paulo" },
  { city: "Rio de Janeiro", country: "Brazil", timezone: "America/Sao_Paulo" },
  { city: "Buenos Aires", country: "Argentina", timezone: "America/Argentina/Buenos_Aires" },
  { city: "Santiago", country: "Chile", timezone: "America/Santiago" },
  { city: "Lima", country: "Peru", timezone: "America/Lima" },
  { city: "Bogotá", country: "Colombia", timezone: "America/Bogota" },
  { city: "Caracas", country: "Venezuela", timezone: "America/Caracas" },
  { city: "London", country: "United Kingdom", timezone: "Europe/London" },
  { city: "Manchester", country: "United Kingdom", timezone: "Europe/London" },
  { city: "Edinburgh", country: "United Kingdom", timezone: "Europe/London" },
  { city: "Dublin", country: "Ireland", timezone: "Europe/Dublin" },
  { city: "Paris", country: "France", timezone: "Europe/Paris" },
  { city: "Berlin", country: "Germany", timezone: "Europe/Berlin" },
  { city: "Munich", country: "Germany", timezone: "Europe/Berlin" },
  { city: "Frankfurt", country: "Germany", timezone: "Europe/Berlin" },
  { city: "Hamburg", country: "Germany", timezone: "Europe/Berlin" },
  { city: "Madrid", country: "Spain", timezone: "Europe/Madrid" },
  { city: "Barcelona", country: "Spain", timezone: "Europe/Madrid" },
  { city: "Rome", country: "Italy", timezone: "Europe/Rome" },
  { city: "Milan", country: "Italy", timezone: "Europe/Rome" },
  { city: "Amsterdam", country: "Netherlands", timezone: "Europe/Amsterdam" },
  { city: "Brussels", country: "Belgium", timezone: "Europe/Brussels" },
  { city: "Zurich", country: "Switzerland", timezone: "Europe/Zurich" },
  { city: "Geneva", country: "Switzerland", timezone: "Europe/Zurich" },
  { city: "Stockholm", country: "Sweden", timezone: "Europe/Stockholm" },
  { city: "Copenhagen", country: "Denmark", timezone: "Europe/Copenhagen" },
  { city: "Oslo", country: "Norway", timezone: "Europe/Oslo" },
  { city: "Helsinki", country: "Finland", timezone: "Europe/Helsinki" },
  { city: "Warsaw", country: "Poland", timezone: "Europe/Warsaw" },
  { city: "Krakow", country: "Poland", timezone: "Europe/Warsaw" },
  { city: "Vienna", country: "Austria", timezone: "Europe/Vienna" },
  { city: "Prague", country: "Czech Republic", timezone: "Europe/Prague" },
  { city: "Budapest", country: "Hungary", timezone: "Europe/Budapest" },
  { city: "Bucharest", country: "Romania", timezone: "Europe/Bucharest" },
  { city: "Lisbon", country: "Portugal", timezone: "Europe/Lisbon" },
  { city: "Athens", country: "Greece", timezone: "Europe/Athens" },
  { city: "Istanbul", country: "Turkey", timezone: "Europe/Istanbul" },
  { city: "Kyiv", country: "Ukraine", timezone: "Europe/Kyiv" },
  { city: "Moscow", country: "Russia", timezone: "Europe/Moscow" },
  { city: "Reykjavik", country: "Iceland", timezone: "Atlantic/Reykjavik" },
  { city: "Tallinn", country: "Estonia", timezone: "Europe/Tallinn" },
  { city: "Riga", country: "Latvia", timezone: "Europe/Riga" },
  { city: "Vilnius", country: "Lithuania", timezone: "Europe/Vilnius" },
  { city: "Cairo", country: "Egypt", timezone: "Africa/Cairo" },
  { city: "Casablanca", country: "Morocco", timezone: "Africa/Casablanca" },
  { city: "Tunis", country: "Tunisia", timezone: "Africa/Tunis" },
  { city: "Lagos", country: "Nigeria", timezone: "Africa/Lagos" },
  { city: "Accra", country: "Ghana", timezone: "Africa/Accra" },
  { city: "Nairobi", country: "Kenya", timezone: "Africa/Nairobi" },
  { city: "Addis Ababa", country: "Ethiopia", timezone: "Africa/Addis_Ababa" },
  { city: "Johannesburg", country: "South Africa", timezone: "Africa/Johannesburg" },
  { city: "Cape Town", country: "South Africa", timezone: "Africa/Johannesburg" },
  { city: "Dubai", country: "United Arab Emirates", timezone: "Asia/Dubai" },
  { city: "Abu Dhabi", country: "United Arab Emirates", timezone: "Asia/Dubai" },
  { city: "Doha", country: "Qatar", timezone: "Asia/Qatar" },
  { city: "Riyadh", country: "Saudi Arabia", timezone: "Asia/Riyadh" },
  { city: "Tel Aviv", country: "Israel", timezone: "Asia/Jerusalem" },
  { city: "Amman", country: "Jordan", timezone: "Asia/Amman" },
  { city: "Beirut", country: "Lebanon", timezone: "Asia/Beirut" },
  { city: "Mumbai", country: "India", timezone: "Asia/Kolkata" },
  { city: "Delhi", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bangalore", country: "India", timezone: "Asia/Kolkata" },
  { city: "Hyderabad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Pune", country: "India", timezone: "Asia/Kolkata" },
  { city: "Karachi", country: "Pakistan", timezone: "Asia/Karachi" },
  { city: "Islamabad", country: "Pakistan", timezone: "Asia/Karachi" },
  { city: "Dhaka", country: "Bangladesh", timezone: "Asia/Dhaka" },
  { city: "Kathmandu", country: "Nepal", timezone: "Asia/Kathmandu" },
  { city: "Colombo", country: "Sri Lanka", timezone: "Asia/Colombo" },
  { city: "Bangkok", country: "Thailand", timezone: "Asia/Bangkok" },
  { city: "Hanoi", country: "Vietnam", timezone: "Asia/Ho_Chi_Minh" },
  { city: "Ho Chi Minh City", country: "Vietnam", timezone: "Asia/Ho_Chi_Minh" },
  { city: "Phnom Penh", country: "Cambodia", timezone: "Asia/Phnom_Penh" },
  { city: "Yangon", country: "Myanmar", timezone: "Asia/Yangon" },
  { city: "Singapore", country: "Singapore", timezone: "Asia/Singapore" },
  { city: "Kuala Lumpur", country: "Malaysia", timezone: "Asia/Kuala_Lumpur" },
  { city: "Jakarta", country: "Indonesia", timezone: "Asia/Jakarta" },
  { city: "Manila", country: "Philippines", timezone: "Asia/Manila" },
  { city: "Hong Kong", country: "Hong Kong", timezone: "Asia/Hong_Kong" },
  { city: "Shanghai", country: "China", timezone: "Asia/Shanghai" },
  { city: "Beijing", country: "China", timezone: "Asia/Shanghai" },
  { city: "Shenzhen", country: "China", timezone: "Asia/Shanghai" },
  { city: "Taipei", country: "Taiwan", timezone: "Asia/Taipei" },
  { city: "Seoul", country: "South Korea", timezone: "Asia/Seoul" },
  { city: "Tokyo", country: "Japan", timezone: "Asia/Tokyo" },
  { city: "Osaka", country: "Japan", timezone: "Asia/Tokyo" },
  { city: "Ulaanbaatar", country: "Mongolia", timezone: "Asia/Ulaanbaatar" },
  { city: "Almaty", country: "Kazakhstan", timezone: "Asia/Almaty" },
  { city: "Tashkent", country: "Uzbekistan", timezone: "Asia/Tashkent" },
  { city: "Sydney", country: "Australia", timezone: "Australia/Sydney" },
  { city: "Melbourne", country: "Australia", timezone: "Australia/Melbourne" },
  { city: "Brisbane", country: "Australia", timezone: "Australia/Brisbane" },
  { city: "Perth", country: "Australia", timezone: "Australia/Perth" },
  { city: "Adelaide", country: "Australia", timezone: "Australia/Adelaide" },
  { city: "Auckland", country: "New Zealand", timezone: "Pacific/Auckland" },
  { city: "Wellington", country: "New Zealand", timezone: "Pacific/Auckland" },
  { city: "Christchurch", country: "New Zealand", timezone: "Pacific/Auckland" },
];
